#!/bin/sh /etc/rc.common

START=80
STOP=10

USE_PROCD=1
PROG=/usr/bin/zeronews

start_instance() {
	local cfg="$1"
	
	local enabled
	config_get_bool enabled "$cfg" enabled 0
	[ "$enabled" -eq 1 ] || return 0

	local token
	config_get token "$cfg" token

	if [ -n "$token" ]; then
		$PROG set token "$token"
	fi

	procd_open_instance zeronews
	procd_set_param command "$PROG" start
	
	procd_set_param respawn
	procd_append_param respawn 3600
	procd_append_param respawn 5
	procd_append_param respawn -1
	
	procd_close_instance
}

start_service() {
	config_load zeronews
	config_foreach start_instance zeronews
}

stop_service() {
	killall zeronews 2>/dev/null
}

restart_service() {
	stop_service
	start_service
}